Issue 290 Part 2
biotite-dev/biotite pull request #301
Opened 2021-03-28 11:12 UTC by MaxGreil

Fixes #290

New __repr__ method for classes:

- CodonTable
- Alignment
- SubstitutionMatrix
- Location
- Feature
- Annotation
- AnnotatedSequence
- Atom

Classes AtomArray and AtomArrayStack can use __repr__ method from respective superclass

### Questions

@padix-key I think for classes CodonTable and SubstitutionMatrix are new __eq__ and __ne__ methods necessary? What do you think?

2021-03-28 14:46 UTC, padix-key commented
Thank you for you effort! :+1:

>  I think for classes CodonTable and SubstitutionMatrix are new eq and ne methods necessary? What do you think?

I agree. Could you add them in this PR?

> Classes AtomArray and AtomArrayStack can use repr method from respective superclass

Could you explain? The class `_AtomArrayBase` has no implemented `__repr__()` method.

For the `CodonTable` class I would like to request to put the `starts` parameter name into the repr-string. I think this makes it clearer for the user what the second parameter means.

2021-03-29 16:45 UTC, MaxGreil commented
> Could you explain? The class _AtomArrayBase has no implemented __repr__() method.

You are right @padix-key , I will also implement the `__repr__` method for classes `AtomArray` and `AtomArrayStack`. Regarding these two classes, should the __repr__` method look like in the discussion for issue #290

`array([
    Atom(array([1.0, 2.0, 3.0]), chain_id="A", res_id=1, ...),
    ...
])
`
?

2021-03-29 18:41 UTC, padix-key commented
I would say so. However, there is a name conflict, as the outer `array()` refers to `structure.array()` and the inner `array()` refers to `numpy.array()`. Maybe we change the inner function to `'np.array([...])'`? For `AtomArrayStack` I would propose something like
```
stack([
    array(...),
    array(...)
])
```

2021-03-30 18:11 UTC, MaxGreil commented
@padix-key I applied the changes

2021-03-31 15:06 UTC, padix-key requested changes
I have a few minor points, which I highlighted in the comments below.

2021-03-31 15:06 UTC, padix-key commented on src/biotite/structure/atoms.py
> +        return f'array([{atoms}])'
Could you put each atom on a separate line with indentation? Currently, the output is
```
array([Atom(...)
...
Atom(...)])
```

but I think
```
array([
    Atom(...)
    ...
    Atom(...)
])
```
would be better readable.

2021-03-31 15:06 UTC, padix-key commented on src/biotite/structure/atoms.py
> +        return f'stack([{arrays}])'
Similar to the comment above, i would like to request another layer of indentation and an empty line between each model to visibly separate them.

2021-04-02 10:48 UTC, padix-key approved these changes
Thank you. I will merge the PR now. The failing AppVeyor tests are an independent issue in the package setup.

2021-04-02 10:48 UTC, merged