[WIP] UniProt
biotite-dev/biotite pull request #309
Opened 2021-05-08 13:43 UTC by MaxGreil

This branch is still Work In Progress.

Implementation of biotite interface to UniProt database.

### Question:
- @padix-key , please have a look here https://www.uniprot.org/help/api%5Fretrieve%5Fentries:
I don't know which databases of UniProt should be accessible and which file formats should be downloadable 
(currently accessible databases are UniProtKB, UniRef and UniPark, file format is fasta)
It seems that available file formats for entries between the databases and even inside the same database can vary

2021-05-10 16:21 UTC, padix-key commented
In the best case, all of these database and formats should be supported. However, I think *UniProtKB* and FASTA + GFF are the most relevant ones. The identifiers seem to be unique for each database: For example all identifiers starting with `UPI` seem to correspond to *Uniparc* entries. Can you confirm this? If this is the case, it is not necessary for the user to set the database name, but it's sufficient to give the entry identifier.

> It seems that available file formats for entries between the databases and even inside the same database can vary

After the database name is inferred from the given identifier(s), the function might check whether the requested format is available for this database and raise a `ValueError` if it is not available.
If the available formats for different entries within the same database vary, I think requesting the file and raise a `RequestError` for an erroneous response is the only solution.

2021-05-18 19:34 UTC, MaxGreil commented
@padix-key I applied your suggested changes. Can you have another look?

2021-05-19 21:28 UTC, padix-key requested changes
Thank you for the improvements. The remaining changes I would like to request are included in this code review.

*UniProt* can also handle queries (https://www.uniprot.org/help/api%5Fqueries) to search in the database. Do you also plan to add support for this API in this PR or is this PR only for the `fetch()` functionality?

2021-05-19 21:28 UTC, padix-key commented on src/biotite/database/uniprot/download.py
> +                _assert_valid_file(r.status_code, id, format)
This if-else-block contains quite a lot of repetitions. Alternatively, you could check for a valid file format at first and then handle the request for any format using the same code.

2021-05-19 21:28 UTC, padix-key commented on src/biotite/database/uniprot/download.py
> +            "Internal server error. Most likely a temporary problem, but if the problem persists please contact us.")
In my opinion *us* sounds like you refer to the Biotite developers. Maybe you could use *UniProt team* instead?

2021-05-19 21:28 UTC, padix-key commented on tests/database/test_uniprot.py
> +pytest.mark.skipif(
`skipif()` is a decorator, so you need to add an ``@`` before it to take effect. Furthermore, I think the two empty lines after the `skipif()` statement should be removed, so it gets clearer, that the decorator is associated to `test_fetch()`.

2021-05-19 21:28 UTC, padix-key commented on tests/database/test_uniprot.py
> +def test_fetch(as_file_like):
Could you also add test cases for an ID from *UniRef* and *UniParc*

2021-05-19 21:28 UTC, padix-key commented on src/biotite/database/uniprot/download.py
> +    Available databases are UniProtKB, UniRef and UniParc
Missing period.

2021-05-19 21:28 UTC, padix-key commented on src/biotite/database/uniprot/download.py
> +def _get_database_name(uid):
I think in *UniProt* the IDs are not called *UIDs* in contrast to the NCBI databases.

2021-05-19 21:28 UTC, padix-key commented on src/biotite/database/uniprot/download.py
> +    ['P12345.fasta', 'Q8K9I1.fasta']
Could you also add the `biotite.database.uniprot` subpackage as test case to `tests/test_doctest.py::test_doctest()`? This way the doctest code output is tested by *pytest*.

2021-05-21 15:56 UTC, MaxGreil commented
@padix-key I applied your requested changes. I also implemented uniprot.query. Can you have another look?

2021-05-22 16:07 UTC, padix-key requested changes
Thank you. I would like to request some changes in `query.py` and I found some typos in `download.py`. In general the code looks good to me :+1:.

2021-05-22 16:07 UTC, padix-key commented on src/biotite/database/uniprot/query.py
> +               "&limit={:}")
This part of the URL can be described more clearly by the `params` parameter of `requests.get()`

2021-05-22 16:07 UTC, padix-key commented on tests/database/test_uniprot.py
> +    assert uniprot.search(query) == ['P62979', 'P0CG47', 'P62987', 'P0CG48', 'P62988']
Could you also add a test for `CompositeQuery`?

2021-05-22 16:07 UTC, padix-key commented on src/biotite/database/uniprot/query.py
> +    """
I think an example code snippet would be helpful here, so the user can additionally see how combination of the `SimpleQuery` works.

2021-05-23 09:18 UTC, MaxGreil commented
@padix-key I applied your changes.

Regarding your question about database responses: 
based on the status codes for UniProt (https://www.uniprot.org/help/api_retrieve_entries), I think this happens in UniProt, too.

Can you please have another look?

2021-05-25 14:32 UTC, padix-key commented
In case of *NCBI Entrez* 'no or malformed data' refers to an *OK* status code, but still the returned file is malformed or empty. So no exception is raised on fetching the file, since the status code is *OK*, but an error occurs downstream, when the file is read.

2021-05-25 17:35 UTC, MaxGreil commented
@padix-key , thank you for the explanation.

Does this mean the 'Warnings' section from uniprot.download.fetch and uniprot.query.search can be removed?

Is the rest of this PR ready to merge?

2021-05-26 06:48 UTC, padix-key commented
> Does this mean the 'Warnings' section from uniprot.download.fetch and uniprot.query.search can be removed?

Yes, I think so.

> Is the rest of this PR ready to merge?

Your code looks good to me, so I will merge it after you remove the warning.

2021-05-26 07:59 UTC, MaxGreil commented
@padix-key , I removed the 'Warnings' section.

2021-05-26 08:08 UTC, padix-key approved these changes
Thank you! I will merge this PR now.

2021-05-26 08:36 UTC, padix-key commented
There is a failing test in the `database.rcsb` module due to outdated data of the PDB. I fixed the test in `biotite-dev biotite/master`. Could you merge it into the PR branch?

2021-05-26 09:00 UTC, MaxGreil commented
@padix-key , I merged the new master branch with uniprot

2021-05-26 15:13 UTC, merged