Fix #333
biotite-dev/biotite pull request #334
Opened 2021-06-27 16:45 UTC by tomtomhdx

This PR changes parameters of the function `plot_nucleotide_secondary_structure`.

The parameter `base_font` is now called `base_text` and the parameter `annotation_font` has been renamed to `annotation_text`.

Instead of a matplotlib `fontdict` they now take any attribute of the respective matplotlib `Text` objects. The attributes can be parsed either as `dict` or as `iterable` to set them either for all relevant `Text` objects or individually.

2021-06-30 06:46 UTC, padix-key requested changes
I have some remaining suggestions for the docstring, but the implmentation looks fine to me. I also tested both parameters in the `dict` and iterable variant and they work as expected in my examples.

2021-06-30 06:46 UTC, padix-key commented on src/biotite/structure/graphics/rna.py
> -    base_font : dict, optional (default: {'size': 'smaller'})
In the code the default value `'small'` is used.

2021-06-30 06:46 UTC, padix-key commented on src/biotite/structure/graphics/rna.py
> +        The *Matplotlib* attributes of the labels denoting the type of
I would replace '\*Matplotlib\* attributes' with 'keyword parameters for the \*Matplotlib\* \`Text\` objects', to clarify the meaning

2021-06-30 06:46 UTC, padix-key commented on src/biotite/structure/graphics/rna.py
> +        The *Matplotlib* attributes of the annotation `Text` objects.
See above.

2021-07-03 12:22 UTC, tomtomhdx commented
Hello,
I made they adjustments to the docstring.

2021-07-05 15:38 UTC, padix-key commented
Thank you. I am merging this PR.

2021-07-05 15:38 UTC, merged