Issue 337
biotite-dev/biotite pull request #341
Opened 2021-07-15 18:38 UTC by MaxGreil

Fixes #337

Implements additional checks for profile constructor.

@padix-key , can you have a look?

2021-07-16 12:18 UTC, padix-key requested changes
Thanks @MaxGreil . I think there is a potentially misleading formulation in the error message.

2021-07-16 12:18 UTC, padix-key commented on src/biotite/sequence/profile.py
> +                f"The given alphabet is shorter ({len(self.alphabet)}) "
It could also be the case, that the alphabet is longer than the number of columns.

2021-07-16 17:54 UTC, MaxGreil commented
Hi @padix-key , I revised the error text. Can you have another look?

2021-07-19 08:10 UTC, padix-key approved these changes
Looks good to me, thank you!

2021-07-19 08:10 UTC, merged