fix #360
biotite-dev/biotite pull request #364
Opened 2021-11-27 20:34 UTC by alex123012

* add desired spacing between elemnets in alignments (function `sequence.graphics.plot_alignment` and its derived functions). for e.g.:
```python
# Code source: Patrick Kunzmann
# License: BSD 3 clause

import matplotlib.pyplot as plt
import biotite.sequence as seq
import biotite.sequence.align as align
import biotite.sequence.io.fasta as fasta
import biotite.database.entrez as entrez
import biotite.sequence.graphics as graphics

# Download and parse protein sequences of avidin and streptavidin
fasta_file = fasta.FastaFile.read(entrez.fetch_single_file(
    ["CAC34569", "ACL82594"], None, "protein", "fasta"
))
for name, sequence in fasta_file.items():
    if "CAC34569" in name:
        avidin_seq = seq.ProteinSequence(sequence)
    elif "ACL82594" in name:
        streptavidin_seq = seq.ProteinSequence(sequence)

# Get BLOSUM62 matrix
matrix = align.SubstitutionMatrix.std_protein_matrix()
# Perform pairwise sequence alignment with affine gap penalty
# Terminal gaps are not penalized
alignments = align.align_optimal(avidin_seq, streptavidin_seq, matrix,
                                 gap_penalty=(-10, -1), terminal_penalty=False)

# Draw first and only alignment
# The color intensity indicates the similiarity
fig = plt.figure(figsize=(8.0, 2.5))
ax = fig.add_subplot(111)
graphics.plot_alignment_similarity_based(
    ax, alignments[0], matrix=matrix, labels=["Avidin", "Streptavidin"],
    show_numbers=True, show_line_position=True, symbol_spacing=5, symbols_per_line=50
)
fig.tight_layout()

plt.show()
```
![image](https://user-images.githubusercontent.com/60808275/143721315-2b1ac634-beea-4247-a4b1-c1f6c85d1676.png)

*  Some code style refactoring in `src/biotite/sequence/graphics/alignment.py` file

2021-11-28 09:58 UTC, alex123012 commented
check symbol_spacing flag in plot_alignment function

2021-11-28 15:42 UTC, padix-key requested changes
Thank you very much for implementing the feature as well as cleaning up the code in the module! I tested the code on some examples from the library and it worked very well in most cases. However, I found any issue in the edge case, where `symbols_per_line` is not a multiple of `symbol_spacing`:

![Figure_1](https://user-images.githubusercontent.com/28051833/143774725-61b808ef-4f25-43e8-af2c-6aa5bf3b7188.png)

Starting from the second line one alignment column is missing at the right end of the line, which also leads to a wrong sequence position number of the rightmost column.

Instead of solving this issue, I think it would be also OK to forbid this edge case, by raising an exception, if  `symbols_per_line` is not a multiple of `symbol_spacing`. I leave this decision up to you.

2021-11-28 15:42 UTC, padix-key commented on src/biotite/sequence/graphics/alignment.py
> +        symbols_to_print = round(spacing_ratio) + symbols_per_line - 1
I do not quite understand the aim of calculating `symbols_to_print` from `symbols_per_line`. I think a comment line would be helpful here.

2021-11-28 15:42 UTC, padix-key commented on src/biotite/sequence/graphics/alignment.py
> +        by variable (github issue #360)
GitHub issues are not referenced in docstrings in Biotite, at least no in the `Parameters` section.

```suggestion
        by variable.
```

2021-11-28 15:42 UTC, padix-key commented on src/biotite/sequence/graphics/alignment.py
> +        by variable (github issue #360)
```suggestion
        by variable.
```

2021-11-28 15:42 UTC, padix-key commented on src/biotite/sequence/graphics/alignment.py
> +        by variable (github issue #360)
```suggestion
        by variable.
```

2021-12-08 18:25 UTC, alex123012 reviewed
Resolve all your comments. Excuse me, because of time, can't fully resolve issue with not multiple symbols_per_line by symbol_spacing. Maybe in the future I'll fix it.

2021-12-11 12:05 UTC, padix-key approved these changes
The PR looks good to me. You may also add yourself to the `CONTRIB.rst`, if you like.

2021-12-13 10:22 UTC, padix-key commented
I already approved the PR. The failing test is caused by an unrelated temporary error in the `database` subpackage. But before I merge, you can add yourself to the list of contributors if you like.

2021-12-15 08:52 UTC, alex123012 commented
> I already approved the PR. The failing test is caused by an unrelated temporary error in the `database` subpackage. But before I merge, you can add yourself to the list of contributors if you like.

Oh, sry, didn't look on tests output, thanks for clarification.

2021-12-28 11:07 UTC, merged