chain id parameter for structure.io.pdbx.get_sequence
biotite-dev/biotite pull request #600
Opened 2024-06-16 16:44 UTC by tjmier

Added a new parameter 'chain_id' to the function 'get_sequence' in the module 'biotite.structure.io.pdbx' to return a dictionary mapping chain_id to the sequence

2024-06-17 08:57 UTC, padix-key requested changes
I added a few further small comments here. If we always return a dictionary, I think the function would be cleaner, if it iterates directly over strand IDs, sequence strings and sequence types instead of splitting it into two for-loops.

2024-06-17 08:57 UTC, padix-key commented on src/biotite/structure/io/pdbx/convert.py
> +        chain ID and each value is the corresponding sequence.
I think we should note here that the chain IDs correspond to `atom_site.auth_asym_id`.

2024-06-17 08:57 UTC, padix-key commented on src/biotite/structure/io/pdbx/convert.py
> +                strand_ids_to_seq_dict[strand_id] = sequences[entity-1]
This lines enumerates, so the first tuple value is not the entity (ID) but the index (always starting at zero).
```suggestion
        for i, strand_ids in enumerate(strand_ids):
            for strand_id in strand_ids:
                strand_ids_to_seq_dict[strand_id] = sequences[i]
```

2024-06-17 08:58 UTC, padix-key commented
Thanks for the PR. I would be in favor of dropping the `chain_id` parameter entirely, and returning always a dictionary. Since Biotite has not reached 1.0, yet, this backwards-incompatible changes would be OK in my opinion.

Note that this would require a few small adjustments of that function call in the tests and documentation (searching for `pdbx.get_sequence` in the code base should find all occurences)

2024-06-17 09:24 UTC, t0mdavid-m commented
I agree with @padix-key. I think we should drop the `chain_id` parameter.

2024-06-17 19:17 UTC, tjmier commented
I sent an additional commit with the suggested changes as I understand them. It is worth noting that there may be instances where entity_poly.pdbx_strand_id  is not equivalent to atom_site.label_asym_id. The structure used in the test function (PDB:5UGO) is an example of this where the strand ID is "T" and the asym_id is "A". This may be an edge case and I am unsure if it will cause issues but its worth mentioning.

2024-06-18 06:17 UTC, padix-key commented on src/biotite/structure/io/pdbx/convert.py
> +    }
In case some converted sequence is `None` in the list comprehension above, `sequences` would have a different length than `strand_ids`.

2024-06-19 00:25 UTC, tjmier commented
Please ignore those commits. I am still learning git and did not think those commits would be sent to this pull request. 
Again, apologies for silly mistakes. A lot of this is new to me.

2024-06-19 12:53 UTC, padix-key commented
No problem. You may also convert this PR to a Draft PR to further indicate that this is work in progress

2024-06-23 04:23 UTC, tjmier commented
The last commit is the one I would like to merge if possible.

2024-06-24 08:36 UTC, padix-key commented
Looks good to me, however, one small adjustment is necessary: With the merge of #552 `residue_coevolution.py` is moved to `doc/examples/scripts/sequence/homology/residue_coevolution.py`. This merge conflict needs to be solved first. Furthermore, you may add yourself to `CONTRIB.rst`, if you like.

2024-06-24 17:05 UTC, closed without merging