Update _split_one_line and remove whitespace parameter
biotite-dev/biotite pull request #686
Opened 2024-10-25 16:28 UTC by xvlaurent

This is an attempt to update _split_one_line function to avoid usage of 'whitespace' parameter and approximation made for '_atom_site' CIF block.

Performance have to be approved with a CI run.

2024-10-27 16:45 UTC, padix-key commented
Hi, thanks for writing this PR together. The benchmarks show that this variant is indeed slightly faster than than the regex-based one. However is still about 40% slower than the fast `expect_whitespace=False` hack. This makes parsing a structure without bonds about 20% slower (as shown above).

Still, I tend towards accepting this change, because it is much cleaner and technically gives the correct result, while currently it does not. If high performance is desired, I would recommend using BinaryCIF anyway. @biotite-dev has anyone a strong opinion about it?

2024-10-27 16:46 UTC, padix-key commented
Fixes #673

2024-10-28 13:21 UTC, xvlaurent commented
I tryed to reduce/optimize the code a bit more, but it seems there is no real gain...

2024-11-01 10:17 UTC, padix-key commented
This is okay, a few other people (including me) already tried that unsuccessfully. After Rust code is introduced into the project (#688), this is probably the first function that is replaced by fast Rust routine.

The PDBx test is currently failing, as it does not expect a generator. Could you either revert to the non-generator variant or adapt the test?

2024-11-12 14:53 UTC, xvlaurent commented
Finally, all tests are fine and branch is up to date!

2024-11-17 15:54 UTC, padix-key requested changes
I only found this small typo. Otherwise the PR looks good to merge!

2024-11-17 15:54 UTC, padix-key commented on tests/database/test_rcsb.py
> +    elif format == "cif":
Good catch!

2024-11-17 15:54 UTC, padix-key commented on src/biotite/structure/io/pdbx/cif.py
> +            striped_line = line.lstrip()
Only a small typo

```suggestion
            stripped_line = line.lstrip()
```

2024-11-17 15:54 UTC, padix-key commented on src/biotite/structure/io/pdbx/cif.py
> +            word, _, line = striped_line.partition(" ")
```suggestion
            word, _, line = stripped_line.partition(" ")
```

2024-11-17 15:54 UTC, padix-key commented on src/biotite/structure/io/pdbx/cif.py
> +                word, _, line = striped_line[1:].partition(separator)
```suggestion
                word, _, line = stripped_line[1:].partition(separator)
```

2024-11-18 08:46 UTC, merged