Add support for space group information when reading and writing pdb files
biotite-dev/biotite pull request #707
Opened 2024-11-27 13:41 UTC by alex-sbaq

Added `get_space_group()` and `set_space_group()` methods as discussed in #689 to support space group and Z value reading/writing for (deprecated) PDB files.

2024-11-28 10:04 UTC, padix-key requested changes
Hi, thanks for implementing this functionality! Could you add a test as well to `tests/structure/io/test_pdb.py`? I think something analogous to `test_conversion()` would work well here: Setting and subsequent retrieving of the space group should return the original space group.

2024-12-12 10:44 UTC, padix-key commented
Thanks for the update! I will give the PR a final review on the weekend.

2024-12-20 13:07 UTC, padix-key requested changes
Thanks for adding the test. I have some minor requests for it, but otherwise, everything looks good!

2024-12-20 13:07 UTC, padix-key commented on tests/structure/io/test_pdb.py
> +    pdb.PDBFile.set_space_group(pdb_file, cryst1)
I think this is more concise and idiomatic.

```suggestion
    pdb_file.set_space_group(cryst1)
```

2024-12-20 13:07 UTC, padix-key commented on tests/structure/io/test_pdb.py
> +    itertools.product(glob.glob(join(data_dir("structure"), "*.pdb")), [None, 1, -1]),
The number of parsed structure models does not influence the `CRYST1` record. Hence for the sake of test speed, I propose to remove the `model` parametrization from this test and always use `model=1` instead.

2024-12-20 13:09 UTC, padix-key commented on tests/structure/io/test_pdb.py
> +    pdb.PDBFile.set_space_group(pdb_file, cryst1)
I think this is more concise and idiomatic.

```suggestion
    pdb_file.set_structure(stack1)
    pdb_file.set_space_group(cryst1)
```

2024-12-20 17:07 UTC, alex-sbaq commented
Thanks for the feedback, @padix-key! I've made the changes to the test - let me know if anything is missing.

2024-12-22 15:33 UTC, padix-key approved these changes
Thanks, the PR looks good to me. I will just wait for the CI to see if the tests pass

2024-12-22 16:51 UTC, merged