Allow ccd residues with missing coords
biotite-dev/biotite pull request #730
Opened 2024-12-27 23:31 UTC by davegrays

There are a number of ligands/residues in the CCD with missing coordinates even in the "ideal" column. These cannot be retrieved now with `structure.info.residue` due to a ValueError that is raised twice and not excepted the second time. Relative to v0, this is new behavior.

This allows these residues to be returned from the ideal coords with nans where missing.

2024-12-31 14:02 UTC, padix-key commented
Hi, from my perspective having a molecule without atom coordinates has barely a benefit. Consequently, getting an exception, that can be easily captured, is more clearer than checking for NaN coordinates in my opinion. However, I would be curious what your use case is.

2024-12-31 19:17 UTC, davegrays commented
@padix-key Makes sense. My use case is that I'm identifying missing atoms in the experimental structure by constructing molecular templates from the CCD (essentially just the list of atom names per residue). So for that I use the CCD's AtomArray and I'm ignoring the coords anyway.

I get your concern tho... what would you think about an optional arg for this in `get_components()` that can propagate to `structure.info.residue`?

2025-01-02 11:36 UTC, Croydon-Brixton commented
I agree with @davegrays that optionally exposing missing atoms in the builtin CCD is useful for building template residues of 'what should be there if all atoms were resolved' and thereby allows checking for missing atoms. 

I like the idea of exposing a flag in `get_components` for this -- here 's a patch MR for this https://github.com/davegrays/biotite/pull/2

2025-01-02 17:05 UTC, davegrays commented
Thanks @Croydon-Brixton ! Merged your patch

2025-01-06 12:38 UTC, padix-key requested changes
Hi, sorry for the delay. I see the point now 👍.

The PR looks mostly good to me, what misses is only a test in `tests/structure/test_info()` where `residue()` loads a molecule with missing coordinates.
Apart from that I added some small code style suggestions to the review.

2025-01-06 12:38 UTC, padix-key commented on src/biotite/structure/info/atoms.py
> +def residue(res_name, allow_missing_coords=False):
Just a nit: Throughout Biotite 'coordinates' is abbreviated with `coord`, so I suggest to use it also here

```suggestion
def residue(res_name, allow_missing_coord=False):
```

2025-01-06 12:38 UTC, padix-key commented on src/biotite/structure/info/atoms.py
> +    allow_missing_coords: bool
```suggestion
    allow_missing_coord: bool, optional
```

2025-01-06 12:38 UTC, padix-key commented on src/biotite/structure/info/atoms.py
> +        are encountered.
In contrast to Markdown Sphinx requires double quoted values to render them as Markdown
```suggestion
        If ``True``, these will be represented as ``nan`` values.
        If ``False``, a ``ValueError`` is raised when missing coordinates
        are encountered.
```

2025-01-06 12:38 UTC, padix-key commented on src/biotite/structure/io/pdbx/convert.py
> +    allow_missing_coords=False,
See above

```suggestion
    allow_missing_coord=False,
```

2025-01-06 12:38 UTC, padix-key commented on src/biotite/structure/io/pdbx/convert.py
> +        are encountered.
```suggestion
    allow_missing_coord: bool, optional
        Whether to allow missing coordinate values in components.
        If ``True``, these will be represented as ``nan`` values.
        If ``False``, a ``ValueError`` is raised when missing coordinates
        are encountered.
```

2025-01-06 12:38 UTC, padix-key commented on src/biotite/structure/io/pdbx/convert.py
> +            if not allow_missing:
I would swap these blocks, i.e. `if allow_missing ... else`, to avoid the unnecessary negation.

2025-01-07 00:52 UTC, davegrays commented
@padix-key thanks for your feedback! all the style changes are implemented and I've added test cases for a few different molecules

2025-01-07 01:37 UTC, davegrays commented
also not sure exactly why but it seems like the ci/cd step that failed was an intermittent network-related issue

2025-01-08 09:08 UTC, padix-key commented
I just run it again, and check if it passes. But I agree, this should have nothing to do with your changes

2025-01-08 09:09 UTC, padix-key approved these changes

2025-01-08 09:11 UTC, padix-key commented
The CI now passes and everything looks good to me. Thank you!

2025-01-08 09:11 UTC, merged